title: HairStyle Guide
email: info@hairstyleguide.com
description: >-
  Learn hairstyling from beginner to pro with step-by-step tutorials.
  Discover simple techniques to advanced styling for all hair types.
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty

collections:
  tutorials:
    output: true
    permalink: /tutorials/:path/

defaults:
  - scope:
      path: ""
      type: "tutorials"
    values:
      layout: "tutorial"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

paginate: 9
paginate_path: "/page/:num/"

exclude:
  - node_modules
  - README.md
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor